project_id = "zrrffsjbfkphridqyais"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54321

[analytics]
enabled = false
port = 54327

[functions.send-notification]
verify_jwt = false

[functions.error-tracking]
verify_jwt = true

[functions.chatbot]
verify_jwt = true